apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: queue-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - queue
          - distributor
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
